# Generated by Django 4.2.3 on 2023-08-09 20:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="title",
                        help_text="Required. Enter name title, please.",
                        max_length=100,
                        verbose_name="title",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="text"
                    ),
                ),
                (
                    "date_create",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="date create",
                    ),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="blogs.blog",
                        verbose_name="blog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("title"),
                models.F("blog"),
                name="blogs_post_title_blog",
                violation_error_message="The title post must be unique in blog!",
            ),
        ),
    ]
