# Generated by Django 4.2.3 on 2023-08-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_post_post_blogs_post_title_blog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-date_create"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                db_index=True,
                default="title",
                help_text="Required. Enter name title, please.",
                max_length=100,
                verbose_name="title",
            ),
        ),
    ]
