# Generated by Django 4.2.3 on 2023-08-10 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_subscriber",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="date subscriber",
                    ),
                ),
            ],
            options={
                "verbose_name": "subscriber",
                "verbose_name_plural": "subscribers",
                "ordering": ["-date_subscriber"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="reserve_USER_ME",
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("username__iexact", "ME"), _negated=True),
                name="reserve_USER_ME",
                violation_error_message="The ME username is reserved. Specify another please.",
            ),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_subscribers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_subscribers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriber",
            constraint=models.UniqueConstraint(
                fields=("user", "author"),
                name="unique_user_author_subscriber",
                violation_error_message="Subscription to the author should be unique!",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriber",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user_id", models.F("author_id")), _negated=True
                ),
                name="check_not_loop_user_author",
                violation_error_message="The user cannot subscribe to his blog!",
            ),
        ),
    ]
