# Generated by Django 4.2.3 on 2023-08-10 10:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_subscriber_remove_user_reserve_user_me_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="reserve_USER_ME",
        ),
        migrations.AddField(
            model_name="user",
            name="subscribed",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subscribed for this user.",
                related_name="my_subscribers",
                through="users.Subscriber",
                to=settings.AUTH_USER_MODEL,
                verbose_name="subscribed",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("username__iexact", "ME"), _negated=True),
                name="reserve_USER_ME",
            ),
        ),
    ]
